### ISSUE TITLE
Merge master into gh-pages?

### ISSUE THREAD

**Issue by sole** [cwilso/AudioContext-MonkeyPatch#4]
Hello Chris

Thanks for this library :-)

A while ago you merged Stuart Memo's nice patch that made the library work with Safari too, but apparently the `gh-pages` branch is the default for this project, and it's the first thing visitors see.

You might have your personal reasons (maybe using gh-pages for publishing) but I wonder if you could merge `master` into `gh-pages` so that people get the latest version _by default_.

**Comment by cwilso** [comment]
Gah.  Sorry about that.

**Comment by cwilso** [comment]
Now removed master branch to avoid this in the future.  (Sorry, BTW, was on vacation.)
